version: '3'

services:
  nuxt:
    ports:
      - 3000:3000
    platform: linux/x86_64
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./front:/front
      - /front/node_modules
    command: >
      ash -c "yarn install && yarn dev"
