version: '3'

services:
  nuxt:
    build: .
    platform: linux/x86_64
    container_name: front
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./front:/front
      - /datsumo-front/node_modules
    command: >
      ash -c "yarn install && yarn dev"
